### PR TITLE
add bietigheim bissingen

### PR DESCRIPTION
**Pull request by the-infinity**
In order to bring bietigheim bissingen to production, we need the static in GeoJSON format.

### CODE REVIEW

**Review by ThorstenFroehlinghaus — COMMENTED** [review]
The file is syntactically correct, but all features have the same coordinates.

**Comment by the-infinity** [comment]
@ThorstenFroehlinghaus that's your task, I don't have lat/lon, I can just give the base structure where you can fill in data manually :)

**Comment by ThorstenFroehlinghaus** [comment]
Ok, I thought this was a generated geojson file

**Comment by the-infinity** [comment]
Closed in favor of https://github.com/ParkenDD/parkapi-static-data/pull/3

**Pull request closed without merging**
